# Generated by Django 3.2.6 on 2021-09-02 17:19

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tumanlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=14, verbose_name='Telefon')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userlar', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Mijoz',
                'verbose_name_plural': 'Mijozlar',
            },
        ),
        migrations.CreateModel(
            name='Uylar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xona_soni', models.IntegerField(blank=True, verbose_name='Xona soni')),
                ('narx', models.IntegerField(blank=True, verbose_name='Narxi($)')),
                ('vaqt', models.DateField(auto_now_add=True, verbose_name='Qushilgan sana')),
                ('aloqa', models.CharField(blank=True, max_length=15, verbose_name='Telefon')),
                ('tumanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tumanda', to='app.tumanlar', verbose_name='Tumanda')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Mijoz', to='app.userdata', verbose_name='Mijoz')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Rasmlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=app.models.image_folder)),
                ('uy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasm', to='app.uylar', verbose_name='rasm')),
            ],
        ),
        migrations.CreateModel(
            name='UylarTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('manzil', models.CharField(blank=True, max_length=200, verbose_name='Manzil')),
                ('turi', models.CharField(blank=True, max_length=50, verbose_name='Turi (dom,hovli)')),
                ('kimga', models.CharField(blank=True, max_length=100, verbose_name='Kim uchun')),
                ('remont', models.CharField(blank=True, max_length=50, verbose_name='Remont')),
                ('qoshimchamalumot', models.CharField(blank=True, max_length=200, verbose_name="Qo'shimcha ma'lumotlar")),
                ('qoshimchajxozlar', models.CharField(max_length=100, verbose_name='Nomi')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app.uylar')),
            ],
            options={
                'verbose_name': 'uylar Translation',
                'db_table': 'app_uylar_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TumanlarTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Nomi')),
                ('slug', models.SlugField(blank=True, verbose_name='slug')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app.tumanlar')),
            ],
            options={
                'verbose_name': 'tumanlar Translation',
                'db_table': 'app_tumanlar_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
