# Generated by Django 3.2.7 on 2021-09-26 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210908_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uylar',
            options={'ordering': ['-id']},
        ),
    ]
